platform :ios, ‘10.0’
use_frameworks!

target ‘DJReader’ do
pod ‘Masonry’, ‘~>1.1.0’
pod ’YYModel’, ’~> 1.0.4’
pod ’AFNetworking’, ’~> 4.0’
pod ’KVOController’
pod ’MBProgressHUD’
pod ’UFKit‘, ‘~> 1.2.4’
pod ’MJExtension‘
pod ’BaiduMobStatCodeless’
#pod ‘Ads-CN’
end
